### ISSUE TITLE
README.md points to old repo

### ISSUE THREAD

**Issue by jerlich** [sanworks/PulsePal#4]
The readme points to the PulsePal/PulsePal repo which is out of date.

The google site Wiki also points to the old repo in the installation instructions.

**Comment by jerlich** [comment]
It's in the linux install page:
https://sites.google.com/site/pulsepalwiki/installing-pulse-pal/linux?authuser=0

**Comment by sanworks** [comment]
Thanks Jeff!
I updated the wiki.
I'll replace the link in the readme with a link to the publication.
